name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup DocFX
      run: dotnet tool install -g docfx --version 2.78.3
    
    - name: Clean output directories
      run: |
        cd docs
        rm -rf _site
        find api -type f \( -name '*.yml' -o -name '.manifest' \) -delete 2>/dev/null || true
    
    - name: Build Documentation
      run: |
        cd docs
        # Run DocFX with --warningsAsErrors to fail the build if there are any warnings
        echo "🔨 Building documentation with DocFX..."
        docfx docfx.json --logLevel Verbose --warningsAsErrors
        echo "✅ Documentation built successfully with no warnings"
    
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_site
  
  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4